sudo: required
services:
  - docker

before_install:
  - docker build -t alazouari/docker-react -f Dockerfile.dev .
script: 
  - docker run -e CI=true alazouari/docker-react npm run test -- --coverage 